### PR TITLE
fix(types): add `string[]` support to `Headers`

### LINKED ISSUE #39: Benzene HTTPRequest is incompatible with Node IncomingMessage
Using Benzene with Node `http` module on a TypeScript code base is a bit cumbersome because Benzene `HTTPRequest` is incompatible with Node `IncomingMessage`. The same is true for `HTTPResponse` and `ServerResponse`.

How do you propose we handle this on a TypeScript code base? Especially since the getting started guide has an example, albeit a JavaScript one, where types are used interchangeably:

```
const server = createServer(async (req, res) => {
  const rawBody = await readBody(req);
  const result = await graphqlHTTP({
    method: req.method,
    headers: req.headers,
    body: parseGraphQLBody(rawBody, req.headers["content-type"]),
  });
  res.writeHead(result.status, result.headers);
  res.end(JSON.stringify(result.payload));
});
```

I'm just looking for best practices, and recommendations :)

### PR DESCRIPTION
**Pull request by rfgamaral**
Closes #39.

### CODE REVIEW

**Comment by hoangvvo** [comment]
Could you please add a test case for this? Thanks!

**Comment by rfgamaral** [comment]
> 
> 
> Could you please add a test case for this? Thanks!

Not exactly sure how to do that, this is just a TypeScript type change, there's no functionality to test.

**Comment by hoangvvo** [comment]
> > Could you please add a test case for this? Thanks!
> 
> Not exactly sure how to do that, this is just a TypeScript type change, there's no functionality to test.

I meant something to check if it is an array in which case we would handle it differently (eg. checking for Array.isArray()). Since we are assuming all of them are strings.

**Comment by hoangvvo** [comment]
Actually, I double checked and it seemed we would be okay without that check.

**Review by hoangvvo — APPROVED** [review]
LGTM

**Comment by rfgamaral** [comment]
@hoangvvo This PR actually introduced a different issue:

image

I think we'll need to be more specific with the types, similar to Node's. I'll submit a fix soon...

**Pull request merged**
